### ISSUE TITLE
Problems With Find devices

### ISSUE THREAD

**Issue by com-master** [seemoo-lab/opendrop#40] opened 2019-12-18 22:04 UTC
Rpi 4 adapter alfa. I start owl and opendrop dont see apple devices with open airdrop. Can you help me with this problem?

**Comment by HiroshiHorie** [comment] 2020-01-05 14:10
I'm having the same issue.

**Comment by redbean-21** [comment] 2020-01-31 06:30
I would love to have advice also. 
I am using Raspberry Pi 3 and added Kali Linux and installed the open airdrop and owl.
There is no error showing but I cannot find device such as Mac book and iPhone 8...

**Comment by schmittner** [comment] 2020-03-19 09:19
Seems to be a duplicate of #28. In general using Wi-Fi channel 6 may give unsatisfactory results

**Closed by schmittner** 2020-03-19 09:19 UTC
